### ISSUE TITLE
Programatically remove any margins-/padding-bottom from the last element in b-ber-reader core

### ISSUE THREAD

**Issue by msimmer** [triplecanopy/b-ber#270]
Mentioned in https://github.com/triplecanopy/b-ber/issues/257

Since the reader uses the CSS column layout, it's sensitive about dangling space at the end of the ultimate section, which can create a 'blank page'. 

We can address this easily with CSS, but this will end up being a recurring issue, and may be a nuisance for layouts with nested elements. 

To do this programatically, we'll need to recursively remove any margin/padding-bottom from the last elements in a chapter

**Comment by calebwaldorf** [comment]
https://github.com/triplecanopy/tc-3.0/issues/1681
